# Generated by Django 4.1.1 on 2022-09-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_passengerprofile_user_alter_staffprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_airline_staff',
            field=models.BooleanField(default=False),
        ),
    ]
