# Generated by Django 4.1.1 on 2022-09-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_is_airline_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('gate_manager', 'gate_manager'), ('check_in_manager', 'check_in_manager'), ('supervisor', 'supervisor')], default='supervisor', max_length=50),
        ),
    ]
