# Generated by Django 4.1.1 on 2022-09-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_staffprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('gate_manager', 'Gate Manager'), ('checkin_manager', 'Check-in manager'), ('supervisor', 'Supervisor')], max_length=50),
        ),
    ]
