version: "3.7"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    image: app:light_airlines
    container_name: light_airlines_container
    command: python airline_erp/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    container_name: postgres_db