# Generated by Django 4.1.1 on 2022-09-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_staffprofile_passengerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('first_class_seats', models.IntegerField()),
                ('business_class_seats', models.IntegerField()),
                ('economy_class_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='FareClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('passenger_first_name', models.CharField(max_length=150)),
                ('passenger_last_name', models.CharField(max_length=150)),
                ('baggage_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lunch', models.BooleanField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('boarding_registered', models.BooleanField()),
                ('checked_in', models.BooleanField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airline.booking')),
                ('fare_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airline.fareclass')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('first_class_seats_occupied', models.IntegerField()),
                ('business_class_seats_occupied', models.IntegerField()),
                ('economy_class_seats_occupied', models.IntegerField()),
                ('first_class_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('business_class_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('economy_class_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airline.airplane')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airline.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.airport')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='account.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_class_discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('business_class_discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('economy_class_discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='airline.flight')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='airline.flight'),
        ),
        migrations.AddField(
            model_name='booking',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='account.passengerprofile'),
        ),
        migrations.CreateModel(
            name='BaggagePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_bag_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('second_bag_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('three_or_more_bags_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fare_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baggage_prices', to='airline.fareclass')),
            ],
        ),
    ]
