# Generated by Django 4.1.1 on 2022-09-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaggagePrices',
            new_name='BaggagePrice',
        ),
    ]
