# Generated by Django 4.1.1 on 2022-09-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_rename_baggageprices_baggageprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='country_code',
            field=models.CharField(default=' ', max_length=2),
        ),
    ]
