# Generated by Django 4.1.1 on 2022-09-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_airport_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='country_code',
            field=models.CharField(max_length=2),
        ),
    ]
