# Generated by Django 4.1.1 on 2022-09-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0004_alter_airport_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.TimeField(null=True),
        ),
    ]
