# Generated by Django 4.1.1 on 2022-09-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0007_alter_flight_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='boarding_registered',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='checked_in',
            field=models.BooleanField(blank=True),
        ),
    ]
