# Generated by Django 4.1.1 on 2022-09-26 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0010_alter_ticket_n_bags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComfortsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('first_bag_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('second_bag_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('three_or_more_bags_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fare_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baggage_prices', to='airline.fareclass')),
            ],
        ),
        migrations.DeleteModel(
            name='BaggagePrice',
        ),
    ]
