# Generated by Django 4.1.1 on 2022-09-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0012_rename_baggage_cost_ticket_baggage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
