# Generated by Django 4.1.1 on 2022-09-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0013_alter_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='boarding_registered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='checked_in',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
