# Generated by Django 4.1.1 on 2022-09-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0015_flight_is_cancelled_alter_ticket_boarding_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='boarding_registered',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='checked_in',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
