# Generated by Django 4.1.1 on 2022-09-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0016_alter_flight_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='business_class_seats_occupied',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='economy_class_seats_occupied',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='first_class_seats_occupied',
            field=models.IntegerField(default=0),
        ),
    ]
