# Generated by Django 4.1.1 on 2022-09-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_staffprofile_role'),
        ('airline', '0018_alter_flight_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='account.staffprofile'),
        ),
    ]
